<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rxjs/4.1.0/rx.all.js"></script>
    <script>
        const source = Rx.Observable.throwError('This is an error!');
        //gracefully handle error, returning observable with error message
        const example = source.catchError(val => of(`I caught: ${val}`));
        //output: 'I caught: This is an error'
        const subscribe = example.subscribe(val => console.log(val));
        
    </script>
</head>
<body>
    
</body>
</html>